print("WECLOME TO PYTHON GUI")
from tkinter import *
cal=Tk()
cal.geometry("370x550")
cal.resizable(0,0)
cal.title("GRADING SYSTEM")
cal.configure(background="light goldenrod2")
Label(cal,font=('helvetica',20,'bold'),text="GRADING SYSTEM",fg="white",background="light goldenrod2").place(x=55,y=0)
Label(cal,font=('helvetica',12,'bold'),text="GRADE",fg="black",background="light goldenrod2").place(x=40,y=50)
Label(cal,font=('helvetica',12,'bold'),text="POINT",fg="black",background="light goldenrod2").place(x=230,y=50)
Label(cal,font=('helvetica',12,'bold'),text="O",fg="black",background="light goldenrod2").place(x=40,y=90)

Label(cal,font=('helvetica',10,'bold'),text="A+",fg="black",background="light goldenrod2").place(x=40,y=130)
Label(cal,font=('helvetica',10,'bold'),text="A",fg="black",background="light goldenrod2").place(x=40,y=170)
Label(cal,font=('helvetica',10,'bold'),text="B+",fg="black",background="light goldenrod2").place(x=40,y=210)
Label(cal,font=('helvetica',10,'bold'),text="B",fg="black",background="light goldenrod2").place(x=40,y=250)
Label(cal,font=('helvetica',10,'bold'),text="C+",fg="black",background="light goldenrod2").place(x=40,y=290)
Label(cal,font=('helvetica',10,'bold'),text="C",fg="black",background="light goldenrod2").place(x=40,y=330)
Label(cal,font=('helvetica',10,'bold'),text="E (Reappear)",fg="black",background="light goldenrod2").place(x=40,y=370)
Label(cal,font=('helvetica',10,'bold'),text="F (Fail)",fg="black",background="light goldenrod2").place(x=40,y=410)
Label(cal,font=('helvetica',10,'bold'),text="G (Backlog)",fg="black",background="light goldenrod2").place(x=40,y=450)
Label(cal,font=('helvetica',10,'bold'),text="I (Result Incomplete)",fg="black",background="light goldenrod2").place(x=40,y=490)

Label(cal,font=('helvetica',10,'bold'),text="10",fg="black",background="light goldenrod2").place(x=230,y=90)

Label(cal,font=('helvetica',10,'bold'),text="9",fg="black",background="light goldenrod2").place(x=230,y=130)
Label(cal,font=('helvetica',10,'bold'),text="8",fg="black",background="light goldenrod2").place(x=230,y=170)
Label(cal,font=('helvetica',10,'bold'),text="7",fg="black",background="light goldenrod2").place(x=230,y=210)
Label(cal,font=('helvetica',10,'bold'),text="6",fg="black",background="light goldenrod2").place(x=230,y=250)
Label(cal,font=('helvetica',10,'bold'),text="5",fg="black",background="light goldenrod2").place(x=230,y=290)
Label(cal,font=('helvetica',10,'bold'),text="4",fg="black",background="light goldenrod2").place(x=230,y=330)
Label(cal,font=('helvetica',10,'bold'),text="0",fg="black",background="light goldenrod2").place(x=230,y=370)
Label(cal,font=('helvetica',10,'bold'),text="0",fg="black",background="light goldenrod2").place(x=230,y=410)
Label(cal,font=('helvetica',10,'bold'),text="0",fg="black",background="light goldenrod2").place(x=230,y=450)
Label(cal,font=('helvetica',10,'bold'),text="0",fg="black",background="light goldenrod2").place(x=230,y=490)

